import { FileType, RankType } from "../components/Board";
import { BoardType, PieceEnum as Piece } from "../types/types";

export const INITIAL_PIECE_POSITIONS: BoardType = {
    1: {
        'a': Piece.Rook,
        'b': Piece.Knight,
        'c': Piece.Bishop,
        'd': Piece.Queen,
        'e': Piece.King,
        'f': Piece.Bishop,
        'g': Piece.Knight,
        'h': Piece.Rook,
    },
    2: {
        'a': Piece.Pawn,
        'b': Piece.Pawn,
        'c': Piece.Pawn,
        'd': Piece.Pawn,
        'e': Piece.Pawn,
        'f': Piece.Pawn,
        'g': Piece.Pawn,
        'h': Piece.Pawn,
    },
    3: {
        'a': undefined,
        'b': undefined,
        'c': undefined,
        'd': undefined,
        'e': undefined,
        'f': undefined,
        'g': undefined,
        'h': undefined,
    },
    4: {
        'a': undefined,
        'b': undefined,
        'c': undefined,
        'd': undefined,
        'e': undefined,
        'f': undefined,
        'g': undefined,
        'h': undefined,
    },
    5: {
        'a': undefined,
        'b': undefined,
        'c': undefined,
        'd': undefined,
        'e': undefined,
        'f': undefined,
        'g': undefined,
        'h': undefined,
    },
    6: {
        'a': undefined,
        'b': undefined,
        'c': undefined,
        'd': undefined,
        'e': undefined,
        'f': undefined,
        'g': undefined,
        'h': undefined,
    },
    7: {
        'a': Piece.Pawn,
        'b': Piece.Pawn,
        'c': Piece.Pawn,
        'd': Piece.Pawn,
        'e': Piece.Pawn,
        'f': Piece.Pawn,
        'g': Piece.Pawn,
        'h': Piece.Pawn,
    },
    8: {
        'a': Piece.Rook,
        'b': Piece.Knight,
        'c': Piece.Bishop,
        'd': Piece.Queen,
        'e': Piece.King,
        'f': Piece.Bishop,
        'g': Piece.Knight,
        'h': Piece.Rook,
    },
}